# Wishlist
# - buffer picker: easy switch to MRU buffer (space+f+enter)
# - file tree
# - eslinting?

theme = "my_vesper"

[editor]
line-number = "relative"
scrolloff = 5
true-color = true
rulers = [80]
auto-format = true # not yet
auto-completion = true
cursorline = true
# cursorcolumn = true
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render=true




[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up



[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

